### ISSUE TITLE
How to deal with protobuf dependency errors from habitat-baselines and transformers_cfg

### ISSUE THREAD

**Issue by dongwxxkchoi** [facebookresearch/partnr-planner#3]
Hi, first of all, congratulations on the amazing work with PARTNR Planner! It's a fantastic project, and I truly appreciate the effort and innovation you've put into it. 😊

I encountered an issue while following the installation guide in your [INSTALLATION.md](https://github.com/facebookresearch/partnr-planner/blob/main/INSTALLATION.md). Specifically, I am facing a dependency conflict related to the `protobuf` package when trying to install the required components.

### Problem:
- `habitat-baselines==0.3.2` requires `protobuf==3.20.1`.
- `transformers_cfg==0.2.1` requires `protobuf>=4.25.2`.
- These conflicting requirements prevent a successful installation in the same Python environment.

### Steps to Reproduce:
1. Follow the installation steps in [INSTALLATION.md](https://github.com/facebookresearch/partnr-planner/blob/main/INSTALLATION.md).
2. Attempt to install both `habitat-baselines` and `transformers_cfg` dependencies in the same environment.
3. Observe the conflict in `protobuf` versions during dependency resolution.

### Environment:
- OS: Ubuntu 22.04 LTS

Thank you for your time and support! I look forward to your guidance on resolving this issue. Please let me know if you need any additional details.

**Comment by 0mdc** [comment]
Hi @dongwxxkchoi , thanks for pointing this out!

It appears that `habitat-baselines` depends on `protobuf==3.20.1` because it's depending on `tensorboard==2.8.0`. This is a pretty old `tensorboard` version, and is not strictly necessary to run the stack.

You can most likely force update your `protobuf` version.

Let me double-check whether this works as expected.

**Comment by 0mdc** [comment]
Hi @dongwxxkchoi , the latest `habitat-lab`/`main` should not have this issue anymore. The conflict should be resolved after re-running `pip install -e habitat-baselines`.
Let me know if the issue persits!
